Add metadata_only to workflow listing queries
temporalio/api pull request #117
Opened 2021-06-17 18:15 UTC by dnr

**What changed?**

Adding a `metadata_only` field to list workflows without fetching the `memo` fields, which can be very large.

**Why?**

To speed up workflow queries.

2021-06-17 18:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/temporalio/api?pullRequest=117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/temporalio/api?pullRequest=117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/temporalio/api?pullRequest=117) it.</sub>

2021-06-17 19:30 UTC, wxing1292 commented on temporal/api/workflow/v1/message.proto
> +    bool has_memo = 15;
the return value should not contain `has_memo`
if the request is asking for all data, then return all data
if the request is asking for only metadata, then only return metadata

2021-06-17 19:31 UTC, wxing1292 requested changes
see my above comments

2021-06-17 20:16 UTC, dnr commented on temporal/api/workflow/v1/message.proto
> +    bool has_memo = 15;
@feedmeapples specifically requested an indication that the memo field is present even when it's not being returned. Is that still needed?

2021-06-18 01:17 UTC, wxing1292 commented on temporal/api/workflow/v1/message.proto
> +    bool has_memo = 15;
> indication that the memo field is present even when it's not being returned
what is the use case?

2021-06-19 18:31 UTC, feedmeapples requested changes

2021-06-19 18:31 UTC, feedmeapples commented on temporal/api/workflow/v1/message.proto
> +    bool has_memo = 15;
use case is to show users placeholder boxes for payloads/memos etc, fields that can be large in size (mbs). Then we can fetch them if user clicks on the placeholder box.
This is similar how github shows diff for big files: 
![image](https://user-images.githubusercontent.com/11838981/122652046-7e530d80-d0f1-11eb-86f7-63c62731f97c.png)
 
 
As for the API design: i think we should do this carefully and make sure it covers Web UI needs (able to show placeholders for inputs, results, payloads, memos).
let's sync on this and keep the PR in draft until we have a solid agreement on this API

cc @stevekinney @sw-yx ^

2021-06-21 22:09 UTC, alexshtin requested changes
I would suggest the following:
1. Rename `metadata_only` to `omit_memo` because it is not clear what is "metadata" in this case. Are `search_attributes` metadata? Or `auto_reset_points`? We will need to define "metadata".
2. For response field, I have two options:
  - Add `is_omitted` field to `Memo` struct. The cons is that we use same struct to persist memo and this field will go to db (minimum overhead, but still).
  - Clear `data` field in every field payload and set encoding to some specific value such as `omitted`.

2021-06-21 22:56 UTC, alexshtin commented
@mfateev what do you think about this?

2021-06-22 03:12 UTC, mfateev commented on temporal/api/workflowservice/v1/request_response.proto
> +    bool metadata_only = 7;
Why are we calling search attributes metadata?
Or we don't return the search attribute values?

2021-06-22 03:12 UTC, mfateev commented on temporal/api/workflow/v1/message.proto
> +    bool has_memo = 15;
If we do this then this field should be part of the Memo structure itself in my opinion. 
Another option is to return memo_size instead of has_memo.

2021-06-22 16:41 UTC, alexshtin commented on temporal/api/workflowservice/v1/request_response.proto
> +    bool metadata_only = 7;
It is for `Memo` not for `SearchAttributes` and this is exactly the problem I pointed out in my [comment](https://github.com/temporalio/api/pull/117#pullrequestreview-688900085). It is not clear what is "metadata" here.

2021-06-22 16:46 UTC, dnr commented
> I would suggest the following:
> 
> 1. Rename `metadata_only` to `omit_memo` because it is not clear what is "metadata" in this case. Are `search_attributes` metadata? Or `auto_reset_points`? We will need to define "metadata" (which is already overloaded term).

Agreed, I like `omit_memo` better.

> 2. For response field, I have two options:
> 
> * Add `is_omitted` field to `Memo` struct. The cons is that we use same struct to persist memo and this field will go to db (minimum overhead, but still).

Sure, this works. I think having a field in Memo that only makes sense in certain contexts isn't a big deal. No extra data is persisted if it's not set.

> * Clear `data` and `metadata` fields in every memo field payload struct and add special key to `Payload.metadata` such as `omitted`. I would vote for this.

The main goal (as I understand it) is to avoid returning large unnecessary data to clients, but if we keep only a single bool present/not-present, I think we can avoid fetching it from the database also. Getting the field names would mean we have to fetch it and then discard it, right? Special key names also feels more clunky than a dedicated field in the proto.

Anyway, updated with new names/fields now.

2021-06-22 17:01 UTC, mfateev commented
I propose to limit the size of the metadata field to less than 1k to completely eliminate this problem. ElasticSearch or any other indexing engines are not designed as blob stores. A user can always store a link to a blob in a real blob store like S3 in the metadata field.

2021-06-22 18:42 UTC, feedmeapples commented on temporal/api/workflow/v1/message.proto
> +    bool has_memo = 15;
How about the following design:

Requests:
1. Add a field to requests "max_payload" so that we can use it as a filter to avoid too large payloads. 
**Reasonings**: 
 - allows to still show `Payload`s that are smaller in size on UI without requiring users to do additional clicking (only actually big payloads will be hidden behind click placeholder) 
 - Instead of depending on server defaults, Allows clients to control how big payloads can be depending on the case
 - Gives flexibility to change the allowed payload size over future

Responses:
1. Always return `Payload` objects
2. Add a field `Size` to `Payload.Metadata equal to `size(Payload.Data`
2. Set `Payload.Data` to `nil` if `size(Payload.Data) > max_payload `

2021-07-01 22:10 UTC, dnr commented
(decided not to go in this direction)

2021-07-01 22:10 UTC, closed without merging