Add first_execution_run_id to missing requests and responses
temporalio/api pull request #151
Opened 2022-02-11 22:48 UTC by bergundy

As discussed on slack, we need `first_execution_run_id` in all of these requests to make them safer.
Also added this to `SignalWithStartWorkflowExecutionResponse` to make using stubs / handles created this way safer.

2022-02-11 23:10 UTC, cretz commented on temporal/api/workflowservice/v1/request_response.proto
> +    // execution chain as this id.
Is not part of the same execution chain, or explicitly if this was not the first in the chain? Can you clarify the doc a bit? Alternative description/approach:

> If set, this will limit the workflow signaled to be in a chain of workflows started with this run ID. This check occurs regardless of `workflow_execution.run_id`, therefore, an error will occur if this is present and `workflow_execution.run_id` is not in that chain.

I presume that's how the `cancel` and `terminate` work too?

2022-02-11 23:16 UTC, cretz reviewed
Would rather not merge this until we get the server impl at least POC'd to confirm no more changes/quirks are needed.

2022-02-11 23:16 UTC, cretz commented on temporal/api/workflowservice/v1/request_response.proto
> +    string first_execution_run_id = 9;
Hrmm, I would have figured this could be used to get the latest for `workflow_execution.workflow_id` instead of just validate.

Is this just for validation? Does that mean there is no reasonable way to say "signal the latest workflow in this chain"? I think that makes our SDK a bit rough. Basically you'll tell people "If you get this error, it means you started a newer workflow of the same workflow ID. Therefore you _somehow_ have to find the run ID for this specific one and go recreate a handle."

2022-02-11 23:24 UTC, bergundy commented on temporal/api/workflowservice/v1/request_response.proto
> +    string first_execution_run_id = 9;
> Does that mean there is no reasonable way to say "signal the latest workflow in this chain"?

To signal the latest, pass in `workflow_id` and `first_execution_run_id`.

Creating a new handle won't change the fact that the current execution chain has already completed.
You can't signal a non-running workflow.

> Therefore you somehow have to find the run ID for this specific one and go recreate a handle.

That's what we want, we're adding this for safety.

2022-02-11 23:27 UTC, cretz commented on temporal/api/workflowservice/v1/request_response.proto
> +    string first_execution_run_id = 9;
> To signal the latest, pass in workflow_id and first_execution_run_id.

So it's not for validation only, it's also used to root the chain? If so, that's perfect. I was just concerned this only validated that the lasted for the workflow ID started with this run, but if it actually uses this run as a root for the chain, perfect.

2022-02-11 23:30 UTC, bergundy commented on temporal/api/workflowservice/v1/request_response.proto
> +    string first_execution_run_id = 9;
yes, IIUC

2022-02-14 17:39 UTC, yiminc approved these changes

2022-02-14 17:39 UTC, yiminc commented on temporal/api/workflowservice/v1/request_response.proto
> +    // execution chain as this id.
I found this comment hard to read. Better to break it into 2 sentences. For example:
If set, this call will error if the target workflow is not part of the same execution chain as this id. Target workflow is specified by `workflow_execution` if run_id is set there, or the most recent run if run_id is not set on `workflow_execution`.

2022-03-31 17:35 UTC, macrogreg requested changes
The PR only addresses a part of the "workflow chain overflow" scenario.
I think we need to hold off on merging it and instead address it holistically with the part of returning the "workflow chain IDs" back to the user.

See here for details: https://github.com/temporalio/temporal/issues/2691

2022-03-31 17:56 UTC, bergundy commented
Yes, I agree @macrogreg.
I didn't want to merge this before verifying the server can implement these API changes anyways.
Let's see if we can get this prioritized.

2024-04-23 17:20 UTC, bergundy commented
We're not doing this anytime soon.

2024-04-23 17:20 UTC, closed without merging