Add batch operation APIs to operator
temporalio/api pull request #197
Opened 2022-07-07 06:26 UTC by yux0

**What changed?**
Add batch operation APIs to operator

**Why?**

**How did you test it?**

**Potential risks**

2022-07-07 13:00 UTC, cretz commented on temporal/api/batch/v1/message.proto
> +package temporal.api.batch.v1;
Do these tiny messages deserve their own package? They seem like they are just messages for starting batch and have no other use. Is there another expected use? Can they not live with the start request? Is the only reason they are in a separate package because we, for whatever reason, are unwilling to use nested messages and, for whatever reason, are unwilling to have additional needed messages that are non-request/response in the request/response proto?

2022-07-07 13:00 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    oneof parameter {
To me, "kind", "type", "operation", etc make more sense than "parameter". But obviously that's subjective and doesn't matter much.

2022-07-07 13:00 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    string workflow_query = 3;
Can you add some documentation on what these fields mean and can accept?

2022-07-07 13:00 UTC, cretz commented on temporal/api/operatorservice/v1/service.proto
> +    rpc StartBatchOperation(StartBatchOperationRequest) returns (StartBatchOperationResponse){
Suggest space between final paren and open brace

2022-07-07 13:00 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    bytes next_page_token = 3;
What can this value be if not returned in `ListBatchOperationsResponse`/

2022-07-07 13:00 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    string operation_type = 1;
Why string and not the enum used in start?

2022-07-07 13:00 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    string processed_workflow_count = 3;
Will operations always be workflows? Maybe `total_operation_count` and `complete_operation_count` instead?

2022-07-07 13:00 UTC, cretz commented on temporal/api/batch/v1/message.proto
> +  string input = 2;
This should probably be payloads. Should we just make sure this accepts everything `temporal.api.workflowservice.v1.SignalWorkflowExecutionRequest` does except the specific workflow execution? (that also justifies moving this to that package, see later comment)

2022-07-07 13:00 UTC, cretz commented on temporal/api/operatorservice/v1/service.proto
> +    rpc StartBatchOperation(StartBatchOperationRequest) returns (StartBatchOperationResponse){
Why not make these part of the workflow service? Not only could you reuse some of the operation request/response values there, it just makes sense to have the RPC calls for, say, signalling one or signalling many workflows together.

2022-07-07 17:10 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +    string operation_type = 1;
Updated to enum

2022-07-07 17:12 UTC, yux0 commented on temporal/api/operatorservice/v1/service.proto
> +    rpc StartBatchOperation(StartBatchOperationRequest) returns (StartBatchOperationResponse){
Cleaned up

2022-07-07 17:54 UTC, cretz commented on temporal/api/operatorservice/v1/service.proto
> +    rpc StartBatchOperation(StartBatchOperationRequest) returns (StartBatchOperationResponse){
Strange to me that I can do the non-batch thing from one service and have to go to the other to do the batch thing. Signalling workflows should be in the workflow service, whether it's one or many workflows IMO.

2022-07-07 21:19 UTC, dnr commented on temporal/api/operatorservice/v1/service.proto
> +    rpc StartBatchOperation(StartBatchOperationRequest) returns (StartBatchOperationResponse){
I think this should be in workflowservice. It's for regular users, not cluster administrators. Basically, if it's something that a user could do themselves (perhaps badly) using the other apis in workflowservice, it should be in workflowservice.

2022-07-07 21:19 UTC, dnr commented on temporal/api/operatorservice/v1/request_response.proto
> +    repeated string job_id = 1;
Might we ever want to return extra information here?

2022-07-08 23:17 UTC, yiminc commented on temporal/api/operatorservice/v1/request_response.proto
> +    string workflow_query = 3;
I would change it to visibility_query, or list_workflow_query, to avoid confusing with workflow query.

2022-07-08 23:25 UTC, yiminc commented on temporal/api/batch/v1/message.proto
> +message BatchOperationSignal {
do you need one for cancel?

2022-07-08 23:25 UTC, yiminc commented on temporal/api/operatorservice/v1/request_response.proto
> +    int32 concurrency = 5;
Maybe some reasonable default value and server side dynamic config is better?

2022-07-08 23:25 UTC, yiminc commented on temporal/api/operatorservice/v1/service.proto
> +    rpc StartBatchOperation(StartBatchOperationRequest) returns (StartBatchOperationResponse){
We discussed this with multiple parties (prod / cloud), and we think operator is a better place. Because we don't expect this to be a common operation that workflow needs. And the scope of this operation could be big so we don't want this to be exposed to everyone. The operator does not need to be cluster admin, it can be namespace admin.

2022-07-11 12:40 UTC, cretz commented on temporal/api/operatorservice/v1/service.proto
> +    rpc StartBatchOperation(StartBatchOperationRequest) returns (StartBatchOperationResponse){
Are y'all gonna make sure this has parity with all the options from workflow service? For example, headers.

I missed the discussion. Personally, I don't think services should be separated by "who might execute them" but "what the service does". If decided already, ok. But I would guess, if we give these a high-level interface in the SDK, they will sit right next to the RPC calls that are in a completely different service in the protos.

2022-07-11 16:34 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +    repeated string job_id = 1;
Good point. I will return a struct and flexible to add extra info.

2022-07-12 22:47 UTC, dnr commented on temporal/api/operatorservice/v1/request_response.proto
> +    repeated temporal.api.workflow.v1.WorkflowExecutionInfo operations = 1;
I meant info specific to the batch operation, like maybe an approximate progress indicator, any errors encountered, etc. Stuff that could be useful when listing these in the UI. But maybe we don't need that.

2022-07-13 02:45 UTC, yux0 commented on temporal/api/batch/v1/message.proto
> +message BatchOperationSignal {
I added a placeholder for cancel. Currently, it doesn't require extra input.

2022-07-13 02:56 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +    repeated temporal.api.workflow.v1.WorkflowExecutionInfo operations = 1;
It will be in the describe batch operation and return per batch operation job. For list, I updated to list with info: id, state, start time and close time.

2022-07-14 05:03 UTC, yiminc approved these changes

2022-07-14 12:32 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +}
This is missing the `identity` value (though maybe you want it at the batch level, unsure). Also, can we add a comment here and in the API to keep this and `temporal.api.workflowservice.v1.SignalWorkflowExecutionRequest` in sync with each other?

2022-07-14 12:32 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +}
This is missing the ability to provide `details`, `identity`, and `first_execution_run_id` (or we can explicitly comment we don't want that here since that's single-termination specific and not here). Also, can we add a comment here and in the API to keep this and `temporal.api.workflowservice.v1.TerminateWorkflowExecutionRequest` in sync with each other?

2022-07-14 12:32 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +}
This is missing the `identity` value (though maybe you want it at the batch level, unsure). Also, can we add a comment here and in the API to keep this and `temporal.api.workflowservice.v1.RequestCancelWorkflowExecutionRequest` in sync with each other?

2022-07-14 12:32 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    temporal.api.enums.v1.BatchOperationType operation_type = 2;
This enum appears redundant. You already have the operation, why do you need a type too?

2022-07-14 12:32 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +}
I think you should provide the failure here, and in the future when we offer something like batch update/query, you might want to offer success values too.

2022-07-19 18:37 UTC, alexshtin requested changes

2022-07-19 18:37 UTC, alexshtin commented on temporal/api/operatorservice/v1/request_response.proto
> +    temporal.api.enums.v1.BatchOperationType operation_type = 2;
At least in go, it is inconvenient to get operation type using `oneof` field. This is why we use similar approach for events and commands. In this case, it is probably not that bad.

2022-07-19 18:37 UTC, alexshtin commented on temporal/api/operatorservice/v1/request_response.proto
> +message BatchOperationInfo {
This file called `request_response` because it contains only `Request` and `Response` objects. Can you move all the rest out? I am ok with `batch_operation.proto` in the same package, but general approach is to move them to special package.

2022-07-19 18:37 UTC, alexshtin commented on temporal/api/operatorservice/v1/request_response.proto
> +message BatchOperationInfo {
Why this is different from `DescribeBatchOperationResponse`?

2022-07-19 21:23 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    temporal.api.enums.v1.BatchOperationType operation_type = 2;
We shouldn't alter our protos because people don't want to do a switch. Generated protos in most languages have easy ways to determine this. Having said that, I know we have this redundancy elsewhere, so I can understand an argument for consistency. It's still unnecessary though.

2022-07-19 21:25 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +message BatchOperationInfo {
I figured it was called "request_response" because it contains request and response objects, and extra needed messages. Why move things out that are never used anywhere else? I don't understand some of these rules. Can the developer make this a child message of the only place it's used instead of unnecessarily moving this once-used item to another package?

2022-07-21 18:16 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +message BatchOperationInfo {
I think it is clean to have in a different proto. Updated.

2022-07-21 18:16 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +message BatchOperationInfo {
This uses in list api and return basic info about the batch operation. The describe batch operation returns the details.

2022-07-21 18:16 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +}
Do you mean the success/ failure of each operation? They will be provided in the describe response.

2022-07-21 18:16 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +}
Updated

2022-07-21 18:17 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +}
Updated

2022-07-21 18:17 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +}
Updated

2022-07-21 22:52 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +}
My mistake here, I thought this represented a single piece of the batch. If we stick with termination, cancellation, and signals then we probably don't need to record batch errors separately. However if we do synchronous updates which have unpersisted errors sometimes.

2022-07-21 23:08 UTC, Sushisource commented on temporal/api/operatorservice/v1/request_response.proto
> +    temporal.api.enums.v1.BatchOperationType operation_type = 2;
I know this is "resolved" but I'd like to throw my 2c out there that I think this is a _really_ bad idea. It allows you to construct invalid proto messages where type says one thing and the operation says another.

I have a hard time interpreting that any other way than as poor design.

Consistency is, I think, a very poor reason to accept bad design. Backwards compatibility, sure, that's a good reason, but we shouldn't repeat the same bad patterns now just because we used them in the past.

2022-07-22 13:23 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +    temporal.api.enums.v1.BatchOperationType operation_type = 2;
> poor design

Yup. Unfortunately we have constantly accepted poor design in favor of consistency (which I disagree with, because I almost always disagree with poor design). This also occurs for messages that are only needed to properly structure request/response types, but sadly we disallow them to live next to their parent request/response type. We also disallow nested messages for no good reason.

2022-07-22 13:24 UTC, cretz commented on temporal/api/operatorservice/v1/request_response.proto
> +message BatchOperationInfo {
Disagree personally, but not a big deal I guess.

2022-07-22 19:55 UTC, yux0 commented on temporal/api/operatorservice/v1/request_response.proto
> +    temporal.api.enums.v1.BatchOperationType operation_type = 2;
I will remove this to only keep the operation.

2022-07-27 03:15 UTC, dnr commented on temporal/api/enums/v1/batch_operation.proto
> +enum BatchOperationType {
can this be removed now that we're just using the `oneof`?

2022-07-27 03:15 UTC, dnr commented on temporal/api/workflowservice/v1/request_response.proto
> +    // Namespace contains the batch operation
```suggestion
    // Namespace that contains the batch operation
```

2022-07-27 03:15 UTC, dnr commented on temporal/api/workflowservice/v1/request_response.proto
> +    // Batch operation type
```suggestion
    // Batch operation state
```

2022-07-27 03:15 UTC, dnr commented on temporal/api/workflowservice/v1/batch_operation.proto
> +  // Batch operation type
```suggestion
  // Batch operation state
```

2022-08-04 16:52 UTC, yux0 commented on temporal/api/enums/v1/batch_operation.proto
> +enum BatchOperationType {
Still used in describe response to indicate the operation type

2022-08-04 16:52 UTC, yux0 commented on temporal/api/workflowservice/v1/request_response.proto
> +    // Namespace contains the batch operation
Updated

2022-08-04 16:53 UTC, yux0 commented on temporal/api/workflowservice/v1/request_response.proto
> +    // Batch operation type
Updated

2022-08-04 16:53 UTC, yux0 commented on temporal/api/workflowservice/v1/batch_operation.proto
> +  // Batch operation type
Updated

2022-08-04 17:24 UTC, dnr commented on temporal/api/enums/v1/batch_operation.proto
> +enum BatchOperationType {
Can the describe response just include the request itself, instead of summarizing it like this? It's not great that we have to keep this in sync with the `oneof` fields

2022-08-04 18:17 UTC, cretz approved these changes

2022-08-04 18:17 UTC, cretz commented on temporal/api/workflowservice/v1/batch_operation.proto
> +// The MIT License
Not sure we need a non-service, non-req/resp file in this folder. Any reason to separate the files here? I don't care _that_ much and easy to move around of course, just curious.

2022-08-04 18:22 UTC, yux0 commented on temporal/api/workflowservice/v1/batch_operation.proto
> +// The MIT License
The other file named request_response.proto and it should contains requests and responses. I think it is cleaner to have specific protos in different files. Agree this can move around so I don't have a strong opinion on this.

2022-08-04 18:43 UTC, cretz commented on temporal/api/workflowservice/v1/batch_operation.proto
> +// The MIT License
Yeah, I don't have a strong opinion. This is good. I am quite happy that these only-for-req/resp messages are in this proto package.

2022-08-04 21:21 UTC, alexshtin approved these changes

2022-08-04 23:02 UTC, yux0 commented on temporal/api/enums/v1/batch_operation.proto
> +// The MIT License
Moved to message.proto.

2022-08-04 23:10 UTC, yux0 commented on temporal/api/workflowservice/v1/request_response.proto
> +    google.protobuf.Timestamp close_time = 5 [(gogoproto.stdtime) = true];
From impl detail, the list only return basic workflow information from list workflow response. The BatchOperationInfo contains workflow information from describe workflow or query workflow.

2022-08-04 23:18 UTC, yux0 commented on temporal/api/workflowservice/v1/batch_operation.proto
> +// The MIT License
Updated

2022-08-04 23:26 UTC, merged