Allow delete proto fields with reserved id and name
temporalio/api pull request #227
Opened 2022-08-22 21:47 UTC by yux0

**What changed?**
Allow delete proto fields with reserved id and name

**Why?**
To allow delete non used fields with reserved id and name

**Breaking changes**

2022-08-22 22:28 UTC, rodrigozhou approved these changes

2022-08-23 17:28 UTC, Sushisource approved these changes

2022-09-06 23:55 UTC, alexshtin requested changes
I am against this. I believe we should continue to adhere `PACKAGE` compatibility level and make breaking changes case by case.

2022-09-06 23:55 UTC, alexshtin commented on buf.yaml
> +    - FIELD_SAME_CTYPE
According to the [doc](https://docs.buf.build/breaking/configuration#except) you can just write:
```suggestion
    - PACKAGE
  except:
    - ENUM_VALUE_NO_DELETE
    - FIELD_NO_DELETE
```

2022-09-06 23:59 UTC, closed without merging