Comment with default page size
temporalio/api pull request #245
Opened 2022-10-26 22:25 UTC by lorensr

2022-10-26 22:26 UTC, cretz approved these changes

2022-11-04 03:30 UTC, mindaugasrukas requested changes
I wouldn't say I like these comments, as they might become outdated and difficult to maintain. Is there a way to have a direct association with the default value?

2022-11-04 03:31 UTC, mindaugasrukas commented
Also, please add a description/reason for the change.

2022-11-07 20:03 UTC, lorensr commented
> I wouldn't say I like these comments, as they might become outdated and difficult to maintain. Is there a way to have a direct association with the default value?

I don't know where they exist or how we'd directly associate

2023-10-22 18:08 UTC, closed without merging